name: noteplus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  uuid: ^3.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.0.11
  flutter_quill: ^11.4.1
  quill_delta: ^3.0.0-nullsafety.2
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  audioplayers: ^6.4.0
  just_audio: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  textfield_tags: ^3.0.1

flutter:
  uses-material-design: true
